name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker containers
      run: docker-compose up -d
    - name: Install dependencies
      run: docker-compose exec appquarium-php-apiuser composer install
    - name: Setup test database
      run: |
        docker-compose exec appquarium-php-apiuser bin/console d:m:s:c
        docker-compose exec appquarium-php-apiuser composer reset-db-test
    - name: Launch tests
      run: docker-compose exec appquarium-php-apiuser bin/phpunit
